; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{227840D2-5A84-4BEF-B16D-2D066F7A2693}
AppName=My Program
AppVersion=1.0
;AppVerName=My Program 1.0
AppPublisher=OME
AppPublisherURL=https://www.example.com/
AppSupportURL=https://www.example.com/
AppUpdatesURL=https://www.example.com/
DefaultDirName={autopf}\My_Program
DisableDirPage=yes
UninstallDisplayIcon={app}\pyside_app_demo.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=mysetup
SetupIconFile=D:\!Orion_Programs\!Source_Controlled\Finances\Source\assets\finance_mode_24dp_75FB4C_FILL0_wght400_GRAD0_opsz24.ico
SolidCompression=yes
WizardStyle=modern dark

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\!Orion_Programs\!Source_Controlled\Finances\Source\pyside_app_demo.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\!Orion_Programs\!Source_Controlled\Finances\Source\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\My Program"; Filename: "{app}\pyside_app_demo.exe"
Name: "{autodesktop}\My Program"; Filename: "{app}\pyside_app_demo.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\pyside_app_demo.exe"; Description: "{cm:LaunchProgram,My Program}"; Flags: nowait postinstall skipifsilent

