# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QHeaderView,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTableView, QTextEdit, QWidget)

from pyqtgraph import PlotWidget

class Ui_OrionsApp(object):
    def setupUi(self, OrionsApp):
        if not OrionsApp.objectName():
            OrionsApp.setObjectName(u"OrionsApp")
        OrionsApp.resize(1540, 800)
        OrionsApp.setTabShape(QTabWidget.TabShape.Triangular)
        self.actionOpen = QAction(OrionsApp)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(OrionsApp)
        self.actionSave.setObjectName(u"actionSave")
        self.actionScreenshot = QAction(OrionsApp)
        self.actionScreenshot.setObjectName(u"actionScreenshot")
        self.actionAbout = QAction(OrionsApp)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(OrionsApp)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(410, 10, 1121, 731))
        self.tabWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.South)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tab.setToolTipDuration(2)
        self.graphBS1 = PlotWidget(self.tab)
        self.graphBS1.setObjectName(u"graphBS1")
        self.graphBS1.setGeometry(QRect(10, 10, 641, 341))
        self.graphBS2 = PlotWidget(self.tab)
        self.graphBS2.setObjectName(u"graphBS2")
        self.graphBS2.setGeometry(QRect(10, 360, 641, 341))
        self.graphBS3 = PlotWidget(self.tab)
        self.graphBS3.setObjectName(u"graphBS3")
        self.graphBS3.setGeometry(QRect(660, 10, 451, 691))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.graphIE3 = PlotWidget(self.tab_2)
        self.graphIE3.setObjectName(u"graphIE3")
        self.graphIE3.setGeometry(QRect(660, 10, 451, 691))
        self.graphIE1 = PlotWidget(self.tab_2)
        self.graphIE1.setObjectName(u"graphIE1")
        self.graphIE1.setGeometry(QRect(10, 10, 641, 341))
        self.graphIE2 = PlotWidget(self.tab_2)
        self.graphIE2.setObjectName(u"graphIE2")
        self.graphIE2.setGeometry(QRect(10, 360, 641, 341))
        self.tabWidget.addTab(self.tab_2, "")
        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 250, 411, 491))
        self.tabWidget_2.setTabPosition(QTabWidget.TabPosition.South)
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tableBS = QTableView(self.tab_3)
        self.tableBS.setObjectName(u"tableBS")
        self.tableBS.setGeometry(QRect(0, 30, 411, 431))
        self.pushButton_add_row = QPushButton(self.tab_3)
        self.pushButton_add_row.setObjectName(u"pushButton_add_row")
        self.pushButton_add_row.setGeometry(QRect(240, 0, 79, 24))
        self.pushButton_saveBS = QPushButton(self.tab_3)
        self.pushButton_saveBS.setObjectName(u"pushButton_saveBS")
        self.pushButton_saveBS.setGeometry(QRect(320, 0, 79, 24))
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.sheetDropdown = QComboBox(self.tab_4)
        self.sheetDropdown.setObjectName(u"sheetDropdown")
        self.sheetDropdown.setGeometry(QRect(0, 0, 151, 24))
        self.sheetLoad = QPushButton(self.tab_4)
        self.sheetLoad.setObjectName(u"sheetLoad")
        self.sheetLoad.setGeometry(QRect(160, 0, 79, 24))
        self.sheetSave = QPushButton(self.tab_4)
        self.sheetSave.setObjectName(u"sheetSave")
        self.sheetSave.setGeometry(QRect(320, 0, 79, 24))
        self.sheetDelete = QPushButton(self.tab_4)
        self.sheetDelete.setObjectName(u"sheetDelete")
        self.sheetDelete.setGeometry(QRect(240, 0, 79, 24))
        self.sheetTable = QTableView(self.tab_4)
        self.sheetTable.setObjectName(u"sheetTable")
        self.sheetTable.setGeometry(QRect(0, 30, 411, 441))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 10, 411, 151))
        self.pushButton_loadmonth = QPushButton(self.groupBox)
        self.pushButton_loadmonth.setObjectName(u"pushButton_loadmonth")
        self.pushButton_loadmonth.setGeometry(QRect(240, 20, 79, 24))
        self.pushButton_savemonth = QPushButton(self.groupBox)
        self.pushButton_savemonth.setObjectName(u"pushButton_savemonth")
        self.pushButton_savemonth.setGeometry(QRect(320, 20, 79, 24))
        self.comboBox_year = QComboBox(self.groupBox)
        self.comboBox_year.setObjectName(u"comboBox_year")
        self.comboBox_year.setGeometry(QRect(10, 20, 80, 24))
        self.comboBox_year.setMaxVisibleItems(12)
        self.comboBox_month = QComboBox(self.groupBox)
        self.comboBox_month.setObjectName(u"comboBox_month")
        self.comboBox_month.setGeometry(QRect(90, 20, 80, 24))
        self.comboBox_month.setMaxVisibleItems(12)
        self.textEdit = QTextEdit(self.groupBox)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 80, 391, 61))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 60, 49, 16))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 160, 411, 81))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 20, 49, 16))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 50, 49, 16))
        self.pushButton_refresh = QPushButton(self.groupBox_2)
        self.pushButton_refresh.setObjectName(u"pushButton_refresh")
        self.pushButton_refresh.setGeometry(QRect(320, 20, 79, 24))
        self.pushButton_refresh.setFlat(False)
        self.comboBox_year_2 = QComboBox(self.groupBox_2)
        self.comboBox_year_2.setObjectName(u"comboBox_year_2")
        self.comboBox_year_2.setGeometry(QRect(50, 20, 80, 24))
        self.comboBox_year_2.setMaxVisibleItems(12)
        self.comboBox_month_2 = QComboBox(self.groupBox_2)
        self.comboBox_month_2.setObjectName(u"comboBox_month_2")
        self.comboBox_month_2.setGeometry(QRect(130, 20, 80, 24))
        self.comboBox_month_2.setMaxVisibleItems(12)
        self.comboBox_month_3 = QComboBox(self.groupBox_2)
        self.comboBox_month_3.setObjectName(u"comboBox_month_3")
        self.comboBox_month_3.setGeometry(QRect(130, 50, 80, 24))
        self.comboBox_month_3.setMaxVisibleItems(12)
        self.comboBox_year_3 = QComboBox(self.groupBox_2)
        self.comboBox_year_3.setObjectName(u"comboBox_year_3")
        self.comboBox_year_3.setGeometry(QRect(50, 50, 80, 24))
        self.comboBox_year_3.setMaxVisibleItems(12)
        OrionsApp.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(OrionsApp)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1540, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        OrionsApp.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(OrionsApp)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        self.statusbar.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.statusbar.setAutoFillBackground(False)
        OrionsApp.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(OrionsApp)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(OrionsApp)
    # setupUi

    def retranslateUi(self, OrionsApp):
        OrionsApp.setWindowTitle(QCoreApplication.translate("OrionsApp", u"MainWindow", None))
        self.actionOpen.setText(QCoreApplication.translate("OrionsApp", u"Set Workspace Directory", None))
        self.actionSave.setText(QCoreApplication.translate("OrionsApp", u"Save", None))
        self.actionScreenshot.setText(QCoreApplication.translate("OrionsApp", u"Screenshot", None))
        self.actionAbout.setText(QCoreApplication.translate("OrionsApp", u"About", None))
#if QT_CONFIG(tooltip)
        self.tab.setToolTip(QCoreApplication.translate("OrionsApp", u"first tab", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("OrionsApp", u"Tab 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("OrionsApp", u"Tab 2", None))
        self.pushButton_add_row.setText(QCoreApplication.translate("OrionsApp", u"Add Row", None))
        self.pushButton_saveBS.setText(QCoreApplication.translate("OrionsApp", u"Save", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("OrionsApp", u"Tab 1", None))
        self.sheetLoad.setText(QCoreApplication.translate("OrionsApp", u"Load", None))
        self.sheetSave.setText(QCoreApplication.translate("OrionsApp", u"Save", None))
        self.sheetDelete.setText(QCoreApplication.translate("OrionsApp", u"Delete", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("OrionsApp", u"Tab 2", None))
        self.groupBox.setTitle(QCoreApplication.translate("OrionsApp", u"Month", None))
        self.pushButton_loadmonth.setText(QCoreApplication.translate("OrionsApp", u"Load", None))
        self.pushButton_savemonth.setText(QCoreApplication.translate("OrionsApp", u"Save", None))
        self.comboBox_year.setPlaceholderText(QCoreApplication.translate("OrionsApp", u"Year", None))
        self.comboBox_month.setPlaceholderText(QCoreApplication.translate("OrionsApp", u"Month", None))
        self.label_2.setText(QCoreApplication.translate("OrionsApp", u"Notes", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("OrionsApp", u"Plotting", None))
        self.label_3.setText(QCoreApplication.translate("OrionsApp", u"From", None))
        self.label_4.setText(QCoreApplication.translate("OrionsApp", u"To", None))
        self.pushButton_refresh.setText(QCoreApplication.translate("OrionsApp", u"Refresh", None))
        self.comboBox_year_2.setPlaceholderText(QCoreApplication.translate("OrionsApp", u"Year", None))
        self.comboBox_month_2.setPlaceholderText(QCoreApplication.translate("OrionsApp", u"Month", None))
        self.comboBox_month_3.setPlaceholderText(QCoreApplication.translate("OrionsApp", u"Month", None))
        self.comboBox_year_3.setPlaceholderText(QCoreApplication.translate("OrionsApp", u"Year", None))
        self.menuFile.setTitle(QCoreApplication.translate("OrionsApp", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("OrionsApp", u"Help", None))
    # retranslateUi

